Hw02 express
DaniilOvsyanniukov/nodejs-homework-rest-api pull request #1
Opened 2021-11-11 11:58 UTC by DaniilOvsyanniukov

2021-11-11 20:54 UTC, KirillKulakow commented on model/index.js
>  // const contacts = require('./contacts.json')
убрать комментарий и отступ в 3 строки

2021-11-11 20:59 UTC, KirillKulakow commented on routes/api/contacts.js
> +  res.status(200)
можешь ответ писать в одну строку res.status(200).json() - но это как кому удобно

2021-11-11 21:07 UTC, KirillKulakow commented on model/index.js
> +  await removeContact(contactId)
не очень корректное решение
лучше найти по индексу, исправить и записать

2021-11-11 21:08 UTC, KirillKulakow commented on model/index.js
> +listContacts()
это зачем?

2021-11-11 21:10 UTC, KirillKulakow commented
По всему твоему приложению я не могу найти/удалить/обновить контакт - пишет Not Found
исправь э ту проблему, если не поймешь почему - напиши мне, я помогу

2021-11-11 21:10 UTC, KirillKulakow requested changes
Need fix

2021-11-12 13:29 UTC, DaniilOvsyanniukov commented on model/index.js
>  // const contacts = require('./contacts.json')
исправил

2021-11-12 13:29 UTC, DaniilOvsyanniukov commented on routes/api/contacts.js
> +  res.status(200)
мне кажется более читабельно когда на разных строках

2021-11-12 13:37 UTC, DaniilOvsyanniukov commented on model/index.js
> +listContacts()
удалить забыл, добавлял для проверки

2021-11-14 14:22 UTC, DaniilOvsyanniukov commented on model/index.js
> +  await removeContact(contactId)
переписал функцию как было сказано

2021-11-14 17:49 UTC, KirillKulakow approved these changes

2021-11-14 18:15 UTC, merged