hw-3 mangodb
DaniilOvsyanniukov/nodejs-homework-rest-api pull request #2
Opened 2021-11-18 11:01 UTC by DaniilOvsyanniukov

2021-11-19 19:04 UTC, KirillKulakow commented on db/connection.js
> +  return mongoose.connect('mongodb+srv://danek:danek1994@cluster0.rjq1f.mongodb.net/db-contacts?retryWrites=true&w=majority')
креды подключения к базам данных должны хранится в конфигах
как минимум в файле .env, который должен быть добавлен в исключения .gitignore

2021-11-19 19:05 UTC, KirillKulakow commented on model/index.js
> +  await Post.findByIdAndUpdate(contactId, { $set: { name, email, phone, favorite: true } })
а если я захочу убрать контакт из списка favorite? почему только true?

2021-11-19 19:10 UTC, KirillKulakow commented on routes/api/contacts.js
>      addContact(newContact)
насколько я понимаю эта функция у тебя асинхронная - что то забыл

2021-11-19 19:12 UTC, KirillKulakow commented on routes/api/contacts.js
> +    if (req.body === {}) {
вспомни JS
неужели {} === {} - будет true?
плохая проверка

2021-11-19 19:13 UTC, KirillKulakow requested changes
Need fix

2021-11-20 11:40 UTC, DaniilOvsyanniukov commented on routes/api/contacts.js
> +    if (req.body === {}) {
Заменил на валидацию JOI

2021-11-20 11:41 UTC, DaniilOvsyanniukov commented on routes/api/contacts.js
>      addContact(newContact)
добавил await к вызову функции

2021-11-20 11:43 UTC, DaniilOvsyanniukov commented on model/index.js
> +  await Post.findByIdAndUpdate(contactId, { $set: { name, email, phone, favorite: true } })
Исправил, если нет поля Favorite то ставит true, если favorite=true оставляет true, если favorite=false то изменяет на false

2021-11-20 11:43 UTC, DaniilOvsyanniukov commented on db/connection.js
> +  return mongoose.connect('mongodb+srv://danek:danek1994@cluster0.rjq1f.mongodb.net/db-contacts?retryWrites=true&w=majority')
Добавил файл .env

2021-11-20 12:26 UTC, KirillKulakow approved these changes

2021-11-20 12:38 UTC, merged