hw-04
DaniilOvsyanniukov/nodejs-homework-rest-api pull request #3
Opened 2021-11-24 17:38 UTC by DaniilOvsyanniukov

2021-11-24 21:00 UTC, KirillKulakow commented on middlewares/authMiddleware.js
> +    const [tokenType, token] = req.headers.authorization.split(' ')
если сделать запрос на пустой список контактов без авторизации сломается приложение

2021-11-24 21:04 UTC, KirillKulakow commented on model/authController.js
> +  const user = await User.findOne({ _id: userId })
в данном методе если юзер не найден вернется undefined - поправь следующую проверку

2021-11-24 21:05 UTC, KirillKulakow commented on model/authController.js
> +  const { email, subscription } = await User.findOne({ _id: userId })
лучше реструктуризацию не делать - если вернется undefined - сломается приложение

2021-11-24 21:07 UTC, KirillKulakow requested changes
Need fix

2021-11-30 13:25 UTC, DaniilOvsyanniukov commented on model/authController.js
> +  const user = await User.findOne({ _id: userId })
Поправил

2021-11-30 13:42 UTC, DaniilOvsyanniukov commented on model/authController.js
> +  const { email, subscription } = await User.findOne({ _id: userId })
исправил

2021-11-30 13:47 UTC, DaniilOvsyanniukov commented on middlewares/authMiddleware.js
> +    const [tokenType, token] = req.headers.authorization.split(' ')
Если нет авторизации, то функция не сделает запрос на контакты, потому что будет ошибка и сообщение 'Please provide a token' и дальше не пойдет

2021-11-30 20:55 UTC, KirillKulakow commented on model/authController.js
> +  if (Object.keys(user).length === 0 || user.token === null) { return undefined }
что возвращает findOne если ничего не нашел? Сможете ли метод Object.keys выполнится?

2021-11-30 20:56 UTC, KirillKulakow requested changes
Need fix

2021-11-30 22:41 UTC, DaniilOvsyanniukov commented on model/authController.js
> +  if (Object.keys(user).length === 0 || user.token === null) { return undefined }
в теории он вернет undefined, но до этого не дойдет потому что предыдущая функция не пропустит и выдаст "not authorized".
Я добавил проверку user на undefined

2021-12-01 21:10 UTC, KirillKulakow commented on model/authController.js
> +  if (Object.keys(user).length === 0 || user.token === null) { return undefined }
хорошо тогда зачем эта проверка?

2021-12-02 20:18 UTC, KirillKulakow approved these changes

2021-12-02 22:12 UTC, merged